apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
  labels:
    app: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware 
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: rkreddybogati/ecommerceapp_nodejs:dev
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: middleware-service
spec:
  selector:
    app: middleware
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3000