apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==

# The data field contains the key-value pairs that you want to store in the Secret.
# The values must be base64 encoded.
